### ISSUE TITLE
Make repo public and some other stuff

### ISSUE THREAD

**Issue by carrotfarmer** [TigerNinja22/Swayde#4]
- [x] Abstract bot token
- [x] Make this repo public
- [x] Set up issue and pull request templates
- [x] Oh and rename this repo.
Close this issue if all of this stuff is done

**Comment by carrotfarmer** [comment]
I feel we shld change the name

**Comment by TigerNinja22** [comment]
I have done that, we need to do the second point now. What is it about??

**Comment by carrotfarmer** [comment]
> I have done that, we need to do the second point now. What is it about??

I'll finish that.

**Comment by carrotfarmer** [comment]
The templates are done I'm closing this issues now.
